name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - ci-test-ghwf

jobs:
  test:
    runs-on: ubuntu-26.04
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.20
              otp: 29.0
            lint: lint

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}

      - name: Install dependencies
        run: mix do deps.get --only $MIX_ENV, deps.compile

      - name: Check that there are no unused dependencies in mix.lock
        run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test

  test_older_elixir:
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.15
              otp: 24.3
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}

      - name: Install dependencies
        run: mix do deps.get --only $MIX_ENV, deps.compile

      - name: Run tests
        run: mix test
